.gitignore, src/model.ts, src/scope.ts, test/unit/model-test.ts
This will allow consumers to inject additional functionality like being
able to live-switch the host or namespace at request time.
=> Extract baseUrl + api root into static method

package.json
Will allow typescript projects importing JSORM to find correct type
declarations.
=> Add typings reference to package.json

.gitignore, src/model.ts, src/request.ts, src/scope.ts, test/unit/model-test.ts
Previously we could only set the JWT token on the underlying fetch()
call. Now any model can enhance the fetch options by overriding
`getFetchOptions()`.
=> Allow arbitrary fetch() options to be specified

src/util/deserialize.ts, test/fixtures.ts, test/unit/model-test.ts
This fixes an issue when looking up/assigning a deep assocation that had
already been assigned to another object would assign an empty copy of
the object instead of the target.  It was doing this because the return
value of the lookup wasn't being used, and instead the function was
inadvertently relying on the modification to the passed in parameter.
=> Fix bug with deeply nested associations

src/util/validation-errors.ts, test/integration/validations-test.ts
Previously the model errors object was being cleared out on save and
then the validator was appending all errors to that empty object after
the result set came back.  This is problematic for frameworks like
vue.js which rely on object observers, as an observer change event is
not fired when the new errors are added unless the developer
specifically requests a deep object watch, with is both computationally
expensive and something that has to be done every time.  This replaces
the behavior by creating a new errors object each time the validator is
run and replacing the one currently on the model with it.
=> Make error validation immutable

src/model.ts, src/util/deserialize.ts, src/util/dirty-check.ts, src/util/write-payload.ts, test/integration/nested-persistence-test.ts, test/unit/model-test.ts
This replicates all the logic from isMarkedForDestruction, but sends the
'dissassociate' method instead of the 'destroy' method. The biggest
thing that might look off here is some duplicative specs, but I'm OK
with this for now.
=> Add isMarkedForDisassociation()

src/attribute.ts, src/main.ts, src/model.ts, src/util/deserialize.ts, src/util/write-payload.ts, test/fixtures.ts, test/integration/persistence-test.ts, types/index.d.ts
You may have an attribute from a selectExtra, like fooCount, that should
not be sent to the server. You can now `attr({ persist: false })` for
these cases.
=> Allow unpersisted attributes

src/model.ts, src/util/dirty-check.ts, src/util/write-payload.ts, test/integration/nested-persistence-test.ts, test/integration/persistence-test.ts, test/unit/model-test.ts
Currently, saving will always send all attributes to the server. This is
a bug; we should only send dirty attributes. This is to better ensure
users don't accidentally overwrite each others' data.
=> When saving, only send dirty attributes

src/configuration.ts, src/model.ts, test/integration/finders-test.ts, test/unit/attributes-test.ts
Though user-facing behavior was (mostly) unaffected, there was an
under-the-hood issue with unrelated models getting each others'
attributes.
The `Model.attributeList` was being shared across all models - you'd see
typescript errors but if you ignored them you would have shared
attribute lists across models. In other words:
```ts
class Person extends ApplicationRecord {
firstName = attr()
}
class Truck extends ApplicationRecord {
wheels = attr()
}
let p = new Person();
p.wheels // typescript error, but p['wheels'] works
// and vice versa for Truck['firstName']
// In a practical sense, here's the real-world bug:
let truck = new Truck({ firstName: 'foo' })
expect(truck['firstName']).to.eq(undefined) // but is actually 'foo'
```
To fix this, ensure we clone the `attributeList` within the …
=> Fix attribute inheritance bug

src/attribute.ts, src/model.ts, test/unit/attributes-test.ts
* Ensures `Object.getOwnPropertyDescriptor(modelInstance, 'attr')` will
accurately return the descriptor. This is needed by VueJS to call the
original getter/setters when setting up the reactive getter/setter
overrides.
* Immediately assigns all attributes - this is because the getter will
set a default when first called. Required by VueJS to track association
arrays.
* Adds `dup()` convensience method.
=> Define attributes on instance, not prototype

src/configuration.ts, src/model.ts, src/scope.ts, src/util/refresh-jwt.ts, test/fixtures.ts, test/integration/authorization-test.ts
If used from the browser, you can now get/set the JWT from localStorage:
```ts
Config.setup({
jwtOwners: [...],
jwtLocalStorage: 'jwt' // or whatever key you'd like to set
})
```
`jwtLocalStorage` is defaulted to `jwt`, meaning this functionality is
**opt-out**. Pass `false` to opt-out.
When enabled, this will automatically set the JWT via local storage, and
update it when the server contains the `X-JWT` header.
=> Optionally add JWT to localStorage

src/model.ts, test/fixtures.ts, test/unit/attributes-test.ts
Adds the `camelizeKeys` option. No breaking changes, as the default is `true`.
I branched off of #20 and I can rebase if/when that is merged to clean up this diff. 
This works (at least according to the tests) but if you have suggestions for a "better way" I am open to changing the implementation.
=> Add support for turning off attribute camelization

src/util/deserialize.ts, test/fixtures.ts, test/integration/relations-test.ts
I added some basic relationship tests in integration because I couldn't find a place that made sense for the camelize tests. Let me know if you know of a better location.
I followed the existing testing patterns as best I could, I hope they aren't too bad.
=> Don't camelize relationship names when camelizeKeys is false

src/attribute.ts, test/unit/attributes-test.ts, test/unit/relationships-test.ts
This PR changes the descriptor for attributes to make them `enumerable`.
I'm opening it up for discussion because, while the diff itself is small, I think there are non-trivial implications.
Tools like `normalizr` rely on [properties being enumerable](https://github.com/paularmstrong/normalizr/blob/master/src/schemas/Object.js#L5) when normalizing their data. This change enable these kinds of tools to work seamlessly since these objects now behave like regular old POJOs
---
NB: `writeable` is not spelled correctly, it's `writable`, (which is why that change is included in the diff). When I added the type annotation, TS immediately threw an error and when I corrected the spelling, tests started failing :(
[Here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Object …
=> [Proposal] Make attributes enumerable

src/util/temp-id.ts, src/util/uuid.ts, src/util/write-payload.ts, test/integration/nested-persistence-test.ts, test/integration/validations-test.ts
Temp IDs don't have to actually be unique - they just have to match up
the relationships/included sections of the payload, and serve as a
reference to an unpersisted object on the client. They should be unique,
not universally or globally unique.
Because of this, let's generate more predictive, simpler temp IDs. This
improves readability, and avoids mocking difficulties.
=> Move to predictive temp IDs

src/configuration.ts, src/model.ts, src/request.ts, src/scope.ts, test/fixtures.ts, test/integration/fetch-middleware-test.ts, test/integration/persistence-test.ts
This is for things like "on any unauthenticated request, redirect to the
login page". You can now add before/after fetch hooks:
```ts
Config.beforeFetch.push(function(url, options) {
options.headers['some-new-header'] = 'foo'
})
Config.afterFetch.push(function(response, json) {
if (response.status === 401) {
throw('abort')
}
})
```
Throwing `abort` will reject the promises as *all* promises are now
rejected: by throwing a RequestError or ResponseError class. These
classes have additional info (like the response object) on them for
additional introspection/handling.
```ts
author.save().catch((e) => {
console.log(e.response.status);
})
```
Finally, this behavior can be overridden at the model level:
```ts
static beforeFetch(url: RequestInfo, options: RequestInit) {
// your overrides here
// …
```
=> Add fetch middleware; improve promise handling

src/custom-extend.ts, src/util/extend.ts
Supports js-dom and faked DOM environments during Node testing. See https://github.com/jsonapi-suite/jsorm/issues/31 for more context.
Thanks to @wadetandy and @richmolj for their help with this.
=> Add stricter comparison between global and window objects.

test/integration/fetch-middleware-test.ts, test/unit/model-test.ts
* on `integration/fetch-middleware-test.ts` removed `.only` so all the tests are ran.
* on `unit/model-test` the actual error message was: `'invalid json response body at http://example.com/api/v1/authors reason: Unexpected end of JSON input'`, so sing contain to have a really _generic_ matcher for the expectation.
=> #35 fixed tests in 5.3

src/util/string.ts, src/util/write-payload.ts, test/integration/nested-persistence-test.ts
We're seeing an issue where a multi-word relationship key (in Rails) is receiving a write payload with a camelized key. The write fails in this case:
```js
{
data: {
id: "1",
relationships: {
specialBooks: {
data: {} // etc
}
}
}
```
This PR adds a test for this behavior, and introduces the `decamelize` string helper.
Definitely open to more elegant ways to do this without decamelizing a string!
=> Ensure relationship keys are de-camelized in write payload

src/index.ts, src/jsonapi-spec.ts, src/proxies/record-proxy.ts, src/request.ts, src/scope.ts, test/integration/fetch-middleware.test.ts, test/integration/relations.test.ts, test/unit/record-proxy.test.ts
Previously the `response.data` of a `Person.find(1).then((response))`
call could be a `Person` instance or null. This is valid according to
the spec, but not helpful for actual development.
Instead, we reject the promise with a relevant error message if the
response is 404 or if `data` is `null`. This way we can have confidence
a successful promise always has not-null `data`
=> Ensure singular calls always resolve a record

src/model.ts, src/util/deserialize.ts, test/integration/dirty-tracking.test.ts, test/unit/model.test.ts
Vue will avoid firing the setter if the getter returns the same value.
This ensures we do not rely on the setter's side-effect, but manually
call reset() to fix the issue.
=> Split isPersisted() and reset()

src/credential-storage.ts, src/model.ts, test/integration/authorization.test.ts, test/unit/model.test.ts
While localStorage is the default backend, I just remembered that the
sessionStorage API has the exact same type signature and can be used
interchangably, so there's no reason to name it in a way that confuses.
=> Rename localStorge => credentialStorage

src/model.ts, src/util/decorators.ts, src/util/enumerables.ts, test/unit/model.test.ts
Including copying all nonEnumerable properties. This works by casting to
enumerable (which cloneDeep requires), then recasting after the clone.
=> Ensure #dup() works correctly

.gitignore, src/model.ts, test/integration/id-map.test.ts
This is probably a better default, following principle of least
surprise, unless we hear otherwise. If you load instanceA, and 1m later
load instanceB with new data from the server, instanceA will change. But
if instanceA has already updated the relevant attribute (it is dirty),
avoid making that change.
Relatedly, if instanceA syncs with a new store update, it would see that
property as dirty, as it didn't match the attributes it was instantiated
with. This commit also ensures synced properties are not seen as dirty.
=> Avoid syncing dirty props on store update

src/request.ts, test/integration/fetch-middleware-test.ts
Certain versions of ie11 will cache the response. This forces a cache
bust in this version of jsorm; 1.x removes this in favor of server-side
caching.
http://mikko.repolainen.fi/posts/2016/12/21/ie-cache-with-fetch-and-aspnet-core.html
=> Ensure cache bust

package.json, src/associations.ts, src/attribute.ts, src/model.ts, src/util/omit.ts, src/util/validation-error-builder.ts, src/util/write-payload.ts, src/validation-errors.ts, test/integration/fetch-middleware.test.ts, test/integration/id-map.test.ts, test/unit/model.test.ts, test/unit/scope.test.ts, test/unit/write-payload.test.ts, tsconfig.json
When consuming JSORM from a typescript 2.8 project there were some
unexpected type errors. In order to resolve these, it was necessary to
upgrade this to the newest version so to better detect the errors and
fix them in this library.
=> Upgrade to typescript 2.8.x

src/scope.ts, test/integration/finders.test.ts
You can pass an array to where, like:
```ts
Post.where({ id: [1, 2, 3] })
```
This will be converted to `?filter[id]=1,2,3`.
This logic was already working, but the type was incorrect. Added a test
for good measure.
=> Fix WhereClause type

src/custom-extend.ts, src/model.ts
The superclass#inherited is causing JSORM v1 objects to have a
prototype of the superclass.
=> Prevent setPrototypeOf from interfering with non-JSORM v0 objects

src/util/parameterize.ts, test/integration/finders.test.ts
When the field or other type of data has html entities in them (i.e.
ampersands), since the data is not encoded for GET requests the
JSORM url will be incidentally broken.  For obvious reasons, POST
requests shouldn't have this issue.
encodeURIComponent encodes a lot of useful characters that doesn't
actually need to be encoded for the brower, so we are only encoding
the tokens that are likely to cause issues.
=> Fix asQueryParams URL encoding issues for GET requests

package.json
These being fixed to a particular version resulted in extra versions of
the dependency in consumers' node_modules tree/output bundles.
=> Relax package versions
